export const samStyle = {
    recipeDescriptor: [
        'All-Rounder',
        'Bazooka Joe\'s',
        'Big Bad',
        'Cadillac',
        'Electric Cadillac',
        'Everything But the Kitchen Sink',
        'Slammin\'',
        'Smoke em if you got em',
        'Twistin\' the Night Away',
        'You-kill-it-we-grill-it',
        'Jamaican',
        'Mediterranean',
        'Ocean Inspired',
        'Ayurvedic',
        'Absolutely Insane',
        'Flavor Blasted',
        'Doritos Locos',
        'XXX-tra Spicy',
        'Livestock Guardian Breed',
    ],
    proteinAdjective: [
        'Air-Chilled',
        'Broasted',
        'Brown Basted',
        'Buffalo',
        'Cajun Blackened',
        'Charred',
        'Coca-Cola Glazed',
        'Cold',
        'Heritage Breed',
        'Island Roasted',
        'Machine Washable',
        'Okinawan',
        'Original',
        'Overboard',
        'Spicy',
        'Texas Style',
        'Toasted',
        'Wasabi Marinated',
        'Flavor Injected',
    ],
    protein: [
        'Beef',
        'Pork',
        'Chicken',
        'Chinese Chicken',
        'Carolina Whole Hog',
        'Sausage',
        'Tofu Buger',
        'Burger',
        'Bacon',
        'Spam Cakes',
        'Tuna',
        'Halibut',
        'Tilapia',
        'Wagyu Steak',
        'Brisket',
        'Baby Back Ribs',
        'St. Louis Ribs',
        'Short Ribs',
        'Ground Beef',
        'Chicken of the Sea',
        'Alligator',
    ],
    joiner: [
        'with',
        'Served on top of',
        'Accompanied by',
        'with a side of',
        'alongside',
        'and',
        'plus',
        'next to',
        'beside',
        'Served with'
    ],
    sideAdjective: [
        'Attractive',
        'Garden Fresh',
        'Very Well Cooked',
        'Professionally Designed',
        'a Whopping Pile of',
        'Just the Right Amount of',
        'Blue Themed',
        'Elevated',
        'Deconstructed',
        'Somewhat Off-Balance',
        'a Tower of',
        'Gorgeous',
        'Lukewarm',
        'Tableside',
    ],
    side: [
        'Potatoes',
        'Scallops',
        'Butter',
        'Candied Yams',
        'Prosecco-Infused Pears',
        'Collard Greens',
        'Edamame',
        'Samosas',
        'Lumpia',
        'Broccolini',
        'Broccoli',
        'Peas and Corn',
        'Ambrosia Salad',
        'Waldorf Salad',
        'Potato Skins'
    ],
    priceSeparator: [
        '-'
    ],
    price: [
        '$6.66',
        '$25',
        '$43 (serves two)',
        '$11.28',
        '$6.66',
        'market price',
        '$25',
        '$22',
        '$27',
        '$9.50 (under 12 only)',
        '$24 (no sharing)',
        '$18.40',
        '$32',
        '$5.99 (only on Tuesdays)',
        '$10 (early bird special)'
    ]
}

export const pyFieriData = {
    "subject_full_name": [
        "Ancho chile-rubbed",
        "Cedar plank",
        "Oven roasted",
        "Caramelized",
        "Reno-style",
        "5 a.m.",
        "General Tso's",
        "Guy's",
        "Guido's",
        "Spicy mesquite",
        "Wagon-wheel",
        "Mama Fieri's",
        "Tomahawk",
        "Santa Fe-style",
        "Twisted",
        "Charcoal-roasted",
        "Spanish Charlie's",
        "Philly-style",
        "Chicken-fried",
        "Spicy",
        "Smokehouse",
        "Tazmanian",
        "Alaskan",
        "Bacon-wrapped",
        "Hong Kong",
        "Sizzling",
        "Tempura",
        "You-kill-it-we-grill-it",
        "Boomtown",
        "Nuthin' fancy",
        "Rajun Cajun",
        "Cilantro-lime",
        "Jamaican me crazy",
        "Pecan-crusted",
        "Nawlins"
    ],
    "what": [
        "chicken",
        "beef",
        "salmon",
        "lamb shoulder",
        "portobello",
        "yellowfin tuna",
        "pork",
        "sirloin",
        "USDA certified angus",
        "catfish",
        "bacon",
        "pork belly",
        "meatloaf",
        "crayfish",
        "tri-tip",
        "tuna",
        "pastrami",
        "kobe",
        "cod",
        "applewood bacon",
        "bison",
        "elk",
        "ostrich"
    ],
    "who": [
        "for two",
        "poppers",
        "platter",
        "lasagna",
        "burger",
        "wrap",
        "bites",
        "fettuccine",
        "shooters",
        "nachos",
        "strips",
        "flatbread",
        "rolls",
        "egg rolls",
        "cannelloni",
        "melt",
        "cakes",
        "Johnny cakes",
        "burrito",
        "jambalaya",
        "buns",
        "mini tacos",
        "bites",
        "chow fun",
        "taquitos",
        "empanadas",
        "mini-calzones",
        "quesadilla",
        "fajitas",
        "sliders"
    ],
    with: [
        'with'
    ], 
    "where": [
        "smoky barbecue",
        "cilantro-lime",
        "kung pao",
        "Hawaiian-style",
        "Jack Daniels",
        "blistered",
        "fiesta",
        "Texas-style",
        "drunken monkey",
        "basmati",
        "Uncle Dino's",
        "three-cheese",
        "chimichurri",
        "Mediterranean",
        "lemon-pepper",
        "wasabi",
        "Santa Rosa-style",
        "roasted garlic",
        "Idaho",
        "parmesan",
        "spinach-artichoke",
        "Jerk-style",
        "campfire",
        "volcano",
        "Buffalo"
    ],
    "how": [
        "aioli",
        "fries",
        "mayo",
        "Tobasco butter",
        "potatoes",
        "shoestring fries",
        "Texas toast",
        "cottage fries",
        "corn on the cob",
        "guacamole",
        "wontons",
        "potato wedges",
        "queso blanco",
        "fries",
        "spuds",
        "tater tots",
        "onion strips",
        "rice pilaf",
        "steamed veggies",
        "cornbread",
        "onion rings",
        "potato skins",
        "beans",
        "potatoes",
        "broccoli spears"
    ],
    dash: [
        '-'
    ],
    "when": [
        "$15",
        "$17 (lunch only)",
        "$25 (comes with choice of soup or salad)",
        "$39",
        "$27",
        "market price",
        "$21",
        "$23.50",
        "$24 (please allow 45 minutes)",
        "$29",
        "$33",
        "$14 (only for kids under 12)",
        "$48",
        "$25 (no sharing)",
        "$19",
        "$18.75",
        "$25"
    ]
}

export const bigJuicyBootiesData = {
    big: [
        'Big'
    ],
    juicy: [
        'JUICY'
    ],
    booties: [
        'BOOTIES'
    ]
}